### ISSUE TITLE
无法自动引入 qrcode.min.js

### ISSUE THREAD

**Issue by pluveto** [zhansingsong/iShare.js#10]
如题

**Comment by pluveto** [comment]
说好的不依赖任何第三方库

**Comment by pluveto** [comment]
GET https://fonts.gstatic.com/s/notosanssc/v8/k3kXo84MPvpLmixcA63oeALhLOCT-xWNm8Hqd37g1OkDRZe7lR4sg1IzSy-MNbE9VH8V.119.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kXo84MPvpLmixcA63oeALhLOCT-xWNm8Hqd37g1OkDRZe7lR4sg1IzSy-MNbE9VH8V.117.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kXo84MPvpLmixcA63oeALhLOCT-xWNm8Hqd37g1OkDRZe7lR4sg1IzSy-MNbE9VH8V.117.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.100.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.100.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.103.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.103.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.105.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.105.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.109.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.109.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.112.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.112.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.31.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.31.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.108.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.108.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.111.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.111.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.106.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.106.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.113.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.113.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.117.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.117.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.115.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.115.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.116.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.116.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.118.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.118.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.114.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.114.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.107.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.107.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kXo84MPvpLmixcA63oeALhLOCT-xWNm8Hqd37g1OkDRZe7lR4sg1IzSy-MNbE9VH8V.107.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kXo84MPvpLmixcA63oeALhLOCT-xWNm8Hqd37g1OkDRZe7lR4sg1IzSy-MNbE9VH8V.107.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kXo84MPvpLmixcA63oeALhLOCT-xWNm8Hqd37g1OkDRZe7lR4sg1IzSy-MNbE9VH8V.114.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kXo84MPvpLmixcA63oeALhLOCT-xWNm8Hqd37g1OkDRZe7lR4sg1IzSy-MNbE9VH8V.114.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kXo84MPvpLmixcA63oeALhLOCT-xWNm8Hqd37g1OkDRZe7lR4sg1IzSy-MNbE9VH8V.118.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kXo84MPvpLmixcA63oeALhLOCT-xWNm8Hqd37g1OkDRZe7lR4sg1IzSy-MNbE9VH8V.118.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200
fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.119.woff2:1 GET https://fonts.gstatic.com/s/notosanssc/v8/k3kIo84MPvpLmixcA63oeALZhaCt9E3g-Lbpcnr20eUBAZG30RMhmVkJXC-1MKE3QRp5zkww.119.woff2 net::ERR_QUIC_PROTOCOL_ERROR 200

**Comment by ititchuan** [comment]
有没有修改引入的 iShare.js的文件名？还有你贴的这是什么？

**Comment by pluveto** [comment]
我的网页在：https://www.xxx.com/archives/abc.html
而 iShare.js 在 https://www.xxx.com/assets/js/iShare.js
然后我发现 iShare.js 它去 https://www.xxx.com/archives/ 寻找 qrcode.min.js 而不是去 https://www.xxx.com/assets/js/。这就是问题所在。

**Comment by ititchuan** [comment]
用最新版iShare.js，而不是iShare.min.js
