### ISSUE TITLE
jiathis.com 他们家的二维码图片不支持 https

### ISSUE THREAD

**Issue by chemzqm** [zhansingsong/iShare.js#2]
建议开放接口，或者依赖 https://github.com/davidshimjs/qrcodejs

**Comment by zhansingsong** [comment]
当初之所以使用jiathis，主要是为了减小库文件的大小。

该接口确实存在某些不足，1.1.0 version修改为：由https://github.com/davidshimjs/qrcodejs库来生成。

**Comment by chemzqm** [comment]
@zhansingsong qrcodejs 这东西体积有点大，而且我们项目里面发现会有浏览器无法正确展示图片的情况，我现在使用自己服务器给 API 来做，感觉问题会少些
