### ISSUE TITLE
getmeta方法有些小小的bug

### ISSUE THREAD

**Issue by sdyk-jym** [zhansingsong/iShare.js#5]
@zhansingsong  您好！

`/**
         * getmeta 通过name获取对应meta的content值
         * @param  {String} name meta的name
         * @return {String}
         */
        getmeta: function(name) {
            var _metas = document.getElementsByTagName('meta');
            for (var i = 0, _item; _item = _metas[i++];) {
                if (_item.getAttribute('name').toLowerCase() === name) {
                    return _item.content;
                }
            }
        },`
这个方法有点小问题，你忽略了一些meta没有name值得情况，比如
`<meta charset="utf-8">`
一般这个会放在第一行，所以`_item.getAttribute('name')`为`null`，导致下面的代码直接走不通，建议你加个判断。谢谢！

**Comment by zhansingsong** [comment]
@sdyk-jym 谢谢反馈，已修复。
